server:
    port: 10820
spring:
    main:
        web-application-type: none
    jmx: 
        enabled: false

javafx:
#    title: 我的javaFx工具集合
    appicons: /images/icon.jpg
    stage:
        resizable: true